[package]
name = "macros"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1", features = ["span-locations"] }
proc-quote = "0.4"
quote = "1"
syn = { version = "1", features = ["visit", "visit-mut"] }
